title: Moeyua
author: Moeyua
language: zh-cn
timezone: Asia/Shanghai
url: http://moeyua.github.io/
theme: typography

# deploy
deploy:
  type: git
  repo: https://github.com/moeyua/moeyua.github.io
  branch: gh-pages

highlight:
  enable: false # we will use the prism plugin instead

plugin:
  - hexo-generator-category-enhance
  - hexo-generator-feed
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-toc
  # ... other plugins you'd like to enable

# Generate archive page
archive_generator:
  per_page: 0

# Generate categories index page and each category page
category_generator:
  per_page: 10
  enable_index_page: true

# Generate tags index page and each tag page
tag_generator:
  per_page: 10
  enable_index_page: true

# Generator atom feed for you website
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
  content_limit:
  content_limit_delim:
  order_by: -date
  icon: https://i.loli.net/2021/11/11/luLsADZJ1BogN4v.jpg
  autodiscovery: true
  template:

# For syntax highlighting
prism_plugin:
  mode: "preprocess"
  theme: "default"
  line_number: true
